name: Trigger Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  random-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git with your account
        run: |
          git config user.name "yaman1337"
          git config user.email "63846784+yaman1337@users.noreply.github.com"

      - name: Make a random commit to trigger Vercel deployment
        run: |
          echo "Triggering Vercel deployment at $(date)" >> random_commit.txt
          git add random_commit.txt
          git commit -m "Random commit to trigger deployment"

      - name: Push with GITHUB_TOKEN
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/your-org/your-repo.git main
